ERROR - 2023-08-14 11:33:55 --> Error connecting to the database: mysqli_sql_exception: Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente.
 in C:\xampp\htdocs\erp\system\Database\MySQLi\Connection.php:174
Stack trace:
#0 C:\xampp\htdocs\erp\system\Database\MySQLi\Connection.php(174): mysqli->real_connect('127.0.0.1', 'root', '', 'prod', 3306, '', 0)
#1 C:\xampp\htdocs\erp\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\erp\system\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\erp\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\htdocs\erp\system\Model.php(268): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\erp\system\BaseModel.php(656): CodeIgniter\Model->doFirst()
#6 C:\xampp\htdocs\erp\app\Models\usuariosRepository.php(27): CodeIgniter\BaseModel->first()
#7 C:\xampp\htdocs\erp\app\Controllers\UsuarioController.php(22): App\Models\usuariosRepository->selectUsuario(Object(App\Models\entities\Usuario))
#8 C:\xampp\htdocs\erp\system\CodeIgniter.php(934): App\Controllers\UsuarioController->logar()
#9 C:\xampp\htdocs\erp\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\UsuarioController))
#10 C:\xampp\htdocs\erp\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\erp\public\index.php(67): CodeIgniter\CodeIgniter->run()
#12 C:\xampp\htdocs\erp\system\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs...')
#13 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente.
 in C:\xampp\htdocs\erp\system\Database\MySQLi\Connection.php:218
Stack trace:
#0 C:\xampp\htdocs\erp\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\erp\system\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\erp\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\xampp\htdocs\erp\system\Model.php(268): CodeIgniter\Database\BaseBuilder->get()
#4 C:\xampp\htdocs\erp\system\BaseModel.php(656): CodeIgniter\Model->doFirst()
#5 C:\xampp\htdocs\erp\app\Models\usuariosRepository.php(27): CodeIgniter\BaseModel->first()
#6 C:\xampp\htdocs\erp\app\Controllers\UsuarioController.php(22): App\Models\usuariosRepository->selectUsuario(Object(App\Models\entities\Usuario))
#7 C:\xampp\htdocs\erp\system\CodeIgniter.php(934): App\Controllers\UsuarioController->logar()
#8 C:\xampp\htdocs\erp\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\UsuarioController))
#9 C:\xampp\htdocs\erp\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\erp\public\index.php(67): CodeIgniter\CodeIgniter->run()
#11 C:\xampp\htdocs\erp\system\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs...')
#12 {main}
CRITICAL - 2023-08-14 11:33:55 --> Unable to connect to the database.
Main connection [MySQLi]: Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente.

in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `login`
WHERE `email` = :email:
AND `senha` = :senha:
 LIMIT 1', [...], false)
 3 SYSTEMPATH\Model.php(268): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(656): CodeIgniter\Model->doFirst()
 5 APPPATH\Models\usuariosRepository.php(27): CodeIgniter\BaseModel->first()
 6 APPPATH\Controllers\UsuarioController.php(22): App\Models\usuariosRepository->selectUsuario(Object(App\Models\entities\Usuario))
 7 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\UsuarioController->logar()
 8 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\UsuarioController))
 9 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
11 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('FCPATH\\index.php')
CRITICAL - 2023-08-14 11:56:39 --> syntax error, unexpected end of file, expecting function (T_FUNCTION) or const (T_CONST)
in APPPATH\Controllers\UsuarioController.php on line 40.
 1 SYSTEMPATH\Autoloader\Autoloader.php(289): CodeIgniter\Autoloader\Autoloader->includeFile('APPPATH\\Controllers\\UsuarioController.php')
 2 SYSTEMPATH\Autoloader\Autoloader.php(267): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Controllers\\UsuarioController')
 3 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('App\\Controllers\\UsuarioController')
 4 [internal function]: spl_autoload_call('App\\Controllers\\UsuarioController')
 5 SYSTEMPATH\CodeIgniter.php(892): class_exists('\\App\\Controllers\\UsuarioController', true)
 6 SYSTEMPATH\CodeIgniter.php(486): CodeIgniter\CodeIgniter->startController()
 7 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
 9 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('FCPATH\\index.php')
CRITICAL - 2023-08-14 11:59:21 --> syntax error, unexpected end of file, expecting function (T_FUNCTION) or const (T_CONST)
in APPPATH\Controllers\UsuarioController.php on line 41.
 1 SYSTEMPATH\Autoloader\Autoloader.php(289): CodeIgniter\Autoloader\Autoloader->includeFile('APPPATH\\Controllers\\UsuarioController.php')
 2 SYSTEMPATH\Autoloader\Autoloader.php(267): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Controllers\\UsuarioController')
 3 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('App\\Controllers\\UsuarioController')
 4 [internal function]: spl_autoload_call('App\\Controllers\\UsuarioController')
 5 SYSTEMPATH\CodeIgniter.php(892): class_exists('\\App\\Controllers\\UsuarioController', true)
 6 SYSTEMPATH\CodeIgniter.php(486): CodeIgniter\CodeIgniter->startController()
 7 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
 9 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('FCPATH\\index.php')
ERROR - 2023-08-14 14:14:30 --> mysqli_sql_exception: Unknown column 'usuario_id' in 'field list' in C:\xampp\htdocs\erp\system\Database\MySQLi\Connection.php:295
Stack trace:
#0 C:\xampp\htdocs\erp\system\Database\MySQLi\Connection.php(295): mysqli->query('INSERT INTO `cl...', 0)
#1 C:\xampp\htdocs\erp\system\Database\BaseConnection.php(691): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `cl...')
#2 C:\xampp\htdocs\erp\system\Database\BaseConnection.php(605): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `cl...')
#3 C:\xampp\htdocs\erp\system\Database\BaseBuilder.php(2309): CodeIgniter\Database\BaseConnection->query('INSERT INTO `cl...', Array, false)
#4 C:\xampp\htdocs\erp\system\Model.php(330): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\erp\system\BaseModel.php(782): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\erp\system\Model.php(730): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\xampp\htdocs\erp\app\Models\ClienteRepository.php(32): CodeIgniter\Model->insert(Array)
#8 C:\xampp\htdocs\erp\app\Controllers\ClienteController.php(28): App\Models\ClienteRepository->inserirCliente(Object(App\Models\entities\Cliente))
#9 C:\xampp\htdocs\erp\system\CodeIgniter.php(934): App\Controllers\ClienteController->cadastrarCliente()
#10 C:\xampp\htdocs\erp\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ClienteController))
#11 C:\xampp\htdocs\erp\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xampp\htdocs\erp\public\index.php(67): CodeIgniter\CodeIgniter->run()
#13 C:\xampp\htdocs\erp\system\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs...')
#14 {main}
CRITICAL - 2023-08-14 14:14:30 --> Unknown column 'usuario_id' in 'field list'
in SYSTEMPATH\Database\BaseConnection.php on line 645.
 1 SYSTEMPATH\Database\BaseBuilder.php(2309): CodeIgniter\Database\BaseConnection->query('INSERT INTO `cliente` (`nome`, `email`, `telefone`, `usuario_id`) VALUES (:nome:, :email:, :telefone:, :usuario_id:)', [...], false)
 2 SYSTEMPATH\Model.php(330): CodeIgniter\Database\BaseBuilder->insert()
 3 SYSTEMPATH\BaseModel.php(782): CodeIgniter\Model->doInsert([...])
 4 SYSTEMPATH\Model.php(730): CodeIgniter\BaseModel->insert([...], true)
 5 APPPATH\Models\ClienteRepository.php(32): CodeIgniter\Model->insert([...])
 6 APPPATH\Controllers\ClienteController.php(28): App\Models\ClienteRepository->inserirCliente(Object(App\Models\entities\Cliente))
 7 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\ClienteController->cadastrarCliente()
 8 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ClienteController))
 9 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
11 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('FCPATH\\index.php')
